# site properties and page defaults
title: OuJiang Pharmacogenomics Lab
subtitle: Andrei V Tkatchenko Group
description: This is description.
header: images/banner.jpg
# 在 _config.yml 中全局设置
header-dark: false
footer: images/background3.jpg
proofer: false

# site social media and other links
links:
  email: andreiv.tkatchenko@ojlab.ac.cn
  orcid:
  google-scholar:
  github: muzier9DESCRIPTION=An engaging 1-3 sentence description of your lab.
  twitter: muzier9DESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: muzier9DESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-multiple-languages-plugin

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

languages: ["en", "cn"]
exclude_from_localizations: ["images"]

# 语言切换配置
i18n:
  default_locale: "en"
  locales: ["en", "cn"]
